# Generated by Django 2.2.6 on 2019-11-09 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personnage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('origine', models.CharField(max_length=100)),
                ('resumer', models.TextField(blank=True, null=True)),
                ('histoire', models.TextField(blank=True, null=True)),
                ('image_filename', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Galerie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images_filename', models.CharField(max_length=255)),
                ('personnage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeries', to='characters.Personnage')),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('visible', 'Visible'), ('cacher', 'Cacher'), ('moderer', 'Modérer')], default='visible', max_length=20)),
                ('moderation_text', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('personnage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='characters.Personnage')),
            ],
        ),
    ]
