# Generated by Django 2.2 on 2019-12-04 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_personnage_publie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personnage',
            old_name='publie',
            new_name='publier',
        ),
    ]
