# Generated by Django 2.2 on 2019-12-06 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_auto_20191204_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentaire',
            old_name='author_name',
            new_name='nom_auteur',
        ),
        migrations.RenameField(
            model_name='commentaire',
            old_name='text',
            new_name='texte',
        ),
        migrations.RenameField(
            model_name='commentaire',
            old_name='moderation_text',
            new_name='texte_moderation',
        ),
    ]
