# Generated by Django 2.2 on 2019-12-05 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_post_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='post',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Thread',
        ),
    ]
